### PR TITLE
Fix the homepage urls in the ecosystem's data.toml

### PR DESCRIPTION
**Pull request by nickelc**
The macro expects `item.homepage_url`

### CODE REVIEW

**Comment by ozkriff** [comment]
:thinking: 

https://github.com/rust-gamedev/arewegameyet/blob/8c2bd06a5924805faad12bd3d19fae70157f50b7/templates/categories/macros.html#L16-L18

https://github.com/rust-gamedev/arewegameyet/blob/8c2bd06a5924805faad12bd3d19fae70157f50b7/templates/categories/macros.html#L23-L25

**Comment by nickelc** [comment]
> thinking

that's for the data sets from github & crates.io

see
https://github.com/rust-gamedev/arewegameyet/blob/8c2bd06a5924805faad12bd3d19fae70157f50b7/templates/categories/macros.html#L30-L35

**Comment by 17cupsofcoffee** [comment]
Yeah, if you look at the `data.toml` for games and resources, they all have `homepage_url`, not `homepage`. So I think this change is correct, and I made a mistake when I was porting the data across to the new format 🤦

**Review by 17cupsofcoffee — APPROVED** [review]

**Comment by 17cupsofcoffee** [comment]
Thank you for the PR!

**Pull request merged**
