### PR TITLE
Add categories for games and resources

### LINKED ISSUE #100: Categorise games
There are now enough games to warrant some categorisation.
My idea would be to divide them in 3/4:

- Commercial
- Game Jam
- Open Source
- Freeware

I think we have a few games that ended up on steam/mobile which are a good fit for the Commercial category. There is also the Chucklefish game, Spellbound, which I think we can already list.

### LINKED ISSUE #252: Split games and resources into categories
Crates are already split into categories.

It seems to me that we should split games and resources into categories too (like action/puzzle/strategy/simulation/etc and articles/videos/tutorials/etc) because otherwise, the main page will explode if we add all the rust games and interesting articles/tutorials to it without any structure.

Optionally, we could show a few randomly selected game/resource cards on the main page, but that another issue.

Related to #157 (_"Sort entries"_)

### PR DESCRIPTION
**Pull request by 17cupsofcoffee**
Fixes #100, and fixes #252.

* Added the ability to create categories for games and resources.
    * For now I've dumped everything into a dummy category - will leave this PR as a draft until people can hash out where stuff should go!
* Aligned all data files on a consistent schema, and updated the readme with instructions
    * Nice side effect of this is that games and resources can now list multiple links (e.g. a homepage and a GitHub repo)
* Made the three site sections a bit more data driven (icons and text are now in config files)/
* Moved the 'categories' path to 'ecosystem' to make it clearer that the path only contains crates.
    * I've set up aliases/redirects, so old links should still work.
* Added myself to the contributor list 😉 

Deploy preview: https://serene-leavitt-3a1e5d.netlify.com/

### CODE REVIEW

**Comment by Lokathor** [comment]
Hmm, each section should probably have a little blurb at the top of the section that describes it in the eyes of the site devs, so that readers can align their expectations accordingly.

**Comment by 17cupsofcoffee** [comment]
> Hmm, each section should probably have a little blurb at the top of the section that describes it in the eyes of the site devs, so that readers can align their expectations accordingly.

Do you mean the three sections on the homepage (i.e. ecosystem, games and resources)?

**Comment by Lokathor** [comment]
yes

**Comment by 17cupsofcoffee** [comment]
I have (belatedly) added support for section descriptions/blurbs - ideas for the content of said blurbs would be welcomed :)

Deploy preview: https://serene-leavitt-3a1e5d.netlify.com/

**Comment by 17cupsofcoffee** [comment]
Based on some feedback from @ozkriff, I've amended the layout of the game categories to be a bit more image-centric. It's now fairly close to the design of the current games section on the site, with the main changes being a) it's still driven by the same logic as the other categories and b) the rows are now always the same height. I think it looks better :)

https://serene-leavitt-3a1e5d.netlify.com/games/category/

**Comment by 17cupsofcoffee** [comment]
One more set of tweaks pushed (I'll stop tinkering now, I swear 😅) - I noticed that the cards on the site were being wrapped in grids, despite the Semantic UI grid component already being able to handle rows by itself. This led to dodgy margins/things looking weird on mobile, so I made things a little more idiomatic.

As part of doing this, I had to restyle the curators section a bit, but I think it looks more consistent with the other sections now. Let me know what you think!

Updated deploy preview: https://serene-leavitt-3a1e5d.netlify.com/

**Comment by ozkriff** [comment]
> For now I've dumped everything into a dummy category - will leave this PR as a draft until people can hash out where stuff should go!

Here's my initial proposal:

- Strategy
  - "A Snake's Tale" - "A (100% Rust) puzzle game about snakes in cramped places"
  - "Astra Terra" - "A real-time base-building strategy game with procedurally generated worlds and an emphasis on simulation and story"
  - "colonize" - "A Dwarf Fortress/Rimworld-like game written in Rust"
  - "Zemeroth" - "A small 2D turn-based hexagonal tactical game made with ggez engine"
  - "Zone of Control" - "A turn-based hexagonal strategy game"
- Puzzle
  - "A Snake's Tale" - "A (100% Rust) puzzle game about snakes in cramped places"
  - "Robo Instructus" - "A puzzle game in which players manoeuvre a robot by issuing instructions via a simple programming language"
  - "Pascal Penguin" - "Pascal Penguin is a 2D grid-based puzzle game with levels designed around slippery ice."
  - "Way of Rhea" - "A puzzle platformer that takes place in a world where you can only interact with objects that match your current color."
- Racing
  - "carambolage" - "Cartoonish style racing game using Rust and OpenGL - highly experimental at its current state"
  - "Vange-rs" - "Rusty Vangers clone"
- RPG
  - "Veloren" - "An open source multiplayer voxel RPG game currently in alpha development."
  - "hematite" - "A simple Minecraft written in Rust with the Piston game engine"
  - "Sulis" - "An RPG with turn based, tactical combat, deep character customization and an engaging storyline."
  - "dose response" - "Dose Response is a roguelike game where you play an addict. Avoid the dangers threatening your mind and body while desperately looking for the next fix."
  - "magog" - "A roguelike game in Rust"
- FPS
  - "HyperZen Training" - "Experimental minimalist game with a special graphical mecanic"
  - "Rust Doom" - "A Doom Renderer written in Rust"
  - "Q³" - "A Quake 3 like game with voxelized destructible maps"
- Card
  - "Solitaire" - "A remake of the Shenzhen Solitaire variant"
- Simulation
  - "Citybound" - "A new city-building game that dares to go beyond everything in its genre"
  - "Evoli" - "An ecosystem simulation game. Achieve the greatest possible eco-diversity without disrupting the equilibrium."
  - "Garden" - "A game centered around really detailed plant growth simulation"
  - "Rust-oids" - "A-life simulator sandbox"
  - "Gaia" - "A program that lets you view the world"
- Platformer:
  - "chirperjax" - "A simple 2D platformer game that demonstrates the use of two Rust crates: Gate and Collider."
  - "Stacked Worlds" - "A game prototype written in Rust, shows how to use specs and nphysics."
- Action
  - "SHAR" - "Network shooter with physics and destructions"
  - "Rocket" - "A toy game in Rust, using Piston. The code is thoroughly commented in order to help people to follow it easily"
  - "ruga" - "A game made in rust"
  - "Llamassacre" - "A jump and bump game for two players made with ggez"
  - "Rostige Schlange" - "Rostige Schlange (\"Rusty Snake\" in German apparently) is a small snake clone, using OpenGL for rendering"
  - "Vigilant Steel" - "A space game using Rust & Piston"
- Other
  - "plantex" - "Open-world exploration game with plants. Everything is procedurally generated"
  - "realm.one" - "A tiled based game written in Rust, uses the Amethyst game engine!"
  - "Reforge" - "Online multiplayer sandbox space ship combat game"
  - "RustyVolley" - "A rewrite of Blobby Volley 2 written in Rust, a blazingly fast, memory safe, thread safe language."

------

It's hard to find _the one_ category for some games. What do you think about tags/labels for genres so one game could have 2-4 of them? Also, tags could be used to mark "Commercial/Game Jam/Open Source/Freeware" stuff from #100.

**Comment by 17cupsofcoffee** [comment]
It may be possible to use tags/taxonomies for this - I'll have a play around with implementing that if people think it'd be a nicer option. It does raise the question of whether they should *replace* categories or be a *supplement* to categories, though :)

**Comment by 17cupsofcoffee** [comment]
After some playing around, I don't think it'd be easy to get Zola's taxonomy support to do what we want without some fairly drastic changes:

* You can only tag pages, and we don't have individual pages for each crate/game/resource (yet?)
* You can't limit taxonomies to a particular section of the site (e.g. if we had a 'puzzle' tag, it'd be at arewegameyet.com/tags/puzzle, not arewegameyet.com/games/tags/puzzle)

So the options we have are:

* Stick with the existing setup of one category per item
    * I could still add basic labels/tags in this case, but I don't think there'd be a way of generating index pages for them (e.g. you wouldn't be able to go to a page with all the things tagged with 'puzzle')
* Split each crate/game/resource out into a seperate file, and then use Zola taxonomies
    * This would be a much more invasive change, but it'd something we'd have to do if we wanted to add pages for individual items anyway, and it'd give us the most flexible setup.

I'm kind of leaning towards the latter being a better long term solution, but given the scale of the change I feel like I should get people's input first!

**Comment by 17cupsofcoffee** [comment]
I've come up with a solution that seems to work kinda nicely:

* Have a `data.toml` for each section of the site (i.e. crates, games, resources), rather than one per category.
* Give each item within a `data.toml` a unique ID.
    * This could be used as the item's slug later on, if we did give each one a page of its own.
* In each category's index file, have a list of all the item IDs that should appear in that category.

This seems to get around the issues listed above:

* Categories are modelled as pages, instead of taxonomies, so they can have rich metadata and nested URLs.
* Items can appear in multiple categories without duplicating data.
* We can have tags without splitting things into a million files, but there's still a pathway for us to do that later on if we want.

**Comment by 17cupsofcoffee** [comment]
I had a go at a first pass of porting categories across to Zola taxonomies and adding items for individual pages, and it's worked out quite well, I think! Bit of a pain converting the data files across, but I was able to automate it quite easily.

For now, I've just done the games section (using the list posted by @ozkriff above as a starting point). If people think this is the right approach, I can convert the other two sections and finish off the templates - if not, I'll revert the commit.

For an example of a game with multiple categories, look at [A Snake's Tale](https://serene-leavitt-3a1e5d.netlify.com/categories/puzzle/) in the puzzle and strategy category.

**Comment by ozkriff** [comment]
I have mixed feelings about this experiment with taxonomies: it definitely works, but feels hacky. It's not that bad to have each game in a separate file, but `+++`, `[taxonomies]` and `[extra]` lines feel weird.

Maybe we should contact Zola's dev (Keats) about our use-case? There's got to be a clean solution for this.

**Comment by 17cupsofcoffee** [comment]
As discussed on Discord, I think we're kinda pushing the limits of Zola here 😅 

I do have an idea for an alternate solution that might be less hacky:

* Revert back to `data.toml` files.
* Add a `categories` field to each item.
* In the page templates, loop through the data to find matching records.
    * Note that Tera (the templating language) doesn't provide an easy way of saying 'filter this collection based on whether each item has a subarray containing a value', so this might end up being a little brute-force-y.

Only downside is that it'd require moving to one data file per section (games, crates, resources) instead of one per category, but I'm not sure that's entirely a bad thing - would be a lot easier to spot duplicate entries that way (e.g. SDL2 already shows up in like 4 files)!

I will give that solution a try, and if we're still not happy with that, we can either go back to the original solution (one category per item) or we can try to make Zola/Tera fit our needs better 😄

**Comment by 17cupsofcoffee** [comment]
I have pushed a version of the code that uses the approach described above 🙂

On the whole it seems a lot simpler - the only bit that makes me sad is the ugly logic for calculating the number of items in a category, but I don't think we can do any better without either changing the data file structure (which would probably make contributing harder) or using a different tool to Zola (much bigger piece of work).

Deploy preview: https://serene-leavitt-3a1e5d.netlify.com/games/puzzle/

**Comment by ozkriff** [comment]
here's my updated proposal:


- "A Snake's Tale" - ["puzzle", "released"]
- "Robo Instructus" - ["puzzle", "released"]
- "Pascal Penguin" - ["puzzle", "released"]
- "Way of Rhea" - ["puzzle"]
- "carambolage" - ["racing"]
- "Vange-rs" - ["racing", "RPG", "open-world"]
- "Astra Terra" - ["strategy", "simulation"]
- "colonize" - ["strategy"]
- "Zemeroth" - ["strategy"]
- "Zone of Control" - ["strategy"]
- "Reforge" - ["strategy"]
- "HyperZen Training" - ["FPS", "released"]
- "Rust Doom" - ["FPS"]
- "Q³" - ["FPS"]
- "Citybound" - ["simulation", "strategy"]
- "Evoli" - ["simulation"]
- "Garden" - ["simulation"]
- "Rust-oids" - ["simulation"]
- "Gaia" - ["simulation"]
- "chirperjax" - ["platformer"]
- "Stacked Worlds" - ["platformer"]
- "Solitaire" - ["card"]
- "SHAR" - ["action"]
- "Rocket" - ["action"]
- "ruga" - ["action"]
- "Llamassacre" - ["action"]
- "Rostige Schlange" - ["action"]
- "Vigilant Steel" - ["action"]
- "plantex" - ["open-world"]
- "realm.one" - ["other"]
- "RustyVolley" - ["other"]
- "Veloren" - ["RPG", "open-world"]
- "hematite" - ["RPG", "open-world"]
- "Sulis" - ["RPG", "strategy"]
- "dose response" - ["RPG"]
- "magog" - ["RPG"]

**Comment by 17cupsofcoffee** [comment]
Sounds good, I'll try to implement that and port the other two sections at some point in the next few days.

**Comment by 17cupsofcoffee** [comment]
Sounds good, I'll try to implement that and port the other two sections at some point in the next few days.

**Comment by 17cupsofcoffee** [comment]
By 'in the next few days', I apparently meant 'tonight' - I've finished converting the site over to the new structure, and have cleaned up my branch a bit :smile:

Only other big change in the most recent commit was that I switched the CI sort script across to using the `pytoml` library instead of `toml` - the latter does not handle inline arrays well (adds trailing commas and uneven spacing all over the place), so it doesn't work with the new addition to the schema.

Possibly might have to rebase once #267 is merged, but in the meantime - r? 🙂

Preview has been updated: https://serene-leavitt-3a1e5d.netlify.com

**Comment by 17cupsofcoffee** [comment]
🎉 🎉 🎉

**Pull request merged**
