### PR TITLE
Added three-d and tri-mesh

### PR DESCRIPTION
**Pull request by asny**

### CODE REVIEW

**Comment by kvark** [comment]
Eh, PR template got ignored.

**Comment by asny** [comment]
> Eh, PR template got ignored.

Eh, what template is that?

**Comment by 17cupsofcoffee** [comment]
This repo doesn't have a PR template - might be getting mixed up with the [newsletter repo](https://github.com/rust-gamedev/rust-gamedev.github.io/pulls)? I also initially thought this was a PR to that 😅

**Comment by kvark** [comment]
lol, indeed, sorry about that!

**Review by 17cupsofcoffee — APPROVED** [review]

**Comment by asny** [comment]
No problem and thanks for review 👍

**Pull request merged**
