### PR TITLE
Add link to podcast

### PR DESCRIPTION
**Pull request by ozkriff**
image

### CODE REVIEW

**Review by 17cupsofcoffee — COMMENTED** [review]
I'm on board with this in principle, although it's been a few months since there were any updates to the podcast. As long as it's still planned to continue, this seems like a worthwhile thing to add.

**Comment by ozkriff** [comment]
> As long as it's still planned to continue, this seems like a worthwhile thing to add.

@patchfx @AngelOnFira, at least one new episode is incoming, right?

**Comment by AngelOnFira** [comment]
Ya, I definitely plan on continuing. @patchfx has had some stuff going on that has taken him off the project for now, but I'm working on doing some independent ones :)

**Review by 17cupsofcoffee — APPROVED** [review]
Then :+1: from me :)

**Pull request merged**
