### PR TITLE
Pageload Improvements

### PR DESCRIPTION
**Pull request by BezPowell**
As mentioned in #398 this PR should increase the pageload performance of the website. In my testing it boosts the pagespeed insights scores by about 20 - 25 for mobile. This is mainly through self-hosting all resources to reduce the number of DNS requests and TLS handshakes to external services.

My apologies for the number of commits being merged. I was trying one optimization at a time and thus needed lots of them to trigger a rebuild on Netlify.

If you have any questions about any of the changes please ping me and I can go over them. I really do need to learn how to make helpful commit messages.

Before:
Screenshot_2021-02-18 PageSpeed Insights(1)

After:
Screenshot_2021-02-18 PageSpeed Insights

### CODE REVIEW

**Comment by BezPowell** [comment]
I'm afraid I've made a couple of more commits to this PR. I've started re factoring the semantic ui CSS to remove unused components - seems to have reduced the filesize by about 250k.

**Comment by 17cupsofcoffee** [comment]
I'll try to have a proper look at this over the weekend, it looks good at first glance.

Just for clarity, are all these Semantic UI files just taken from https://github.com/Semantic-Org/Semantic-UI-CSS (with file extensions changes for SCSS)?

**Comment by BezPowell** [comment]
> I'll try to have a proper look at this over the weekend, it looks good at first glance.
> 
> Just for clarity, are all these Semantic UI files just taken from https://github.com/Semantic-Org/Semantic-UI-CSS (with file extensions changes for SCSS)?

Sorry, should have clarified that one. They are all the files taken from the official download, just renamed so they can be imported.

**Review by 17cupsofcoffee — COMMENTED** [review]
Some initial thoughts:

* `_semantic.min.scss` should probably just be called `_semantic.scss`, since it's not minified any more.
* The `_site.scss` component has an import for the Google Fonts version of the Lato font - do we need to remove that?
    * Perhaps we could move the `font-face` definitions there? Then `_semantic.scss` could just be  for enabling/disabling chunks.
* It seems a bit weird that `static/assets` contains `js/semantic` and `semantic` - ideally I would like there to be an obvious seperation between our stuff and the stuff we've taken from Semantic UI, rather than it being spread across multiple folders.
* I don't believe we use `loader`, `placeholder`, `reveal`, `message`, `embed` or `video` - unless they're used under the hood by some of the JS stuff?

**Comment by BezPowell** [comment]
> Some initial thoughts:
> 
>     * `_semantic.min.scss` should probably just be called `_semantic.scss`, since it's not minified any more.
> 
>     * The `_site.scss` component has an import for the Google Fonts version of the Lato font - do we need to remove that?
>       
>       * Perhaps we could move the `font-face` definitions there? Then `_semantic.scss` could just be  for enabling/disabling chunks.
> 
>     * It seems a bit weird that `static/assets` contains `js/semantic` and `semantic` - ideally I would like there to be an obvious seperation between our stuff and the stuff we've taken from Semantic UI, rather than it being spread across multiple folders.
> 
>     * I don't believe we use `loader`, `placeholder`, `reveal`, `message`, `embed` or `video` - unless they're used under the hood by some of the JS stuff?
> 
> 
> The fact that this is largely just a copy and paste from the official repo is nice - reduces the maintanance burden if we do pull these into the repo.

I've just pushed a commit up to address those issues. I totally agree on the separation of concerns and thank you for spotting the google fonts creeping back in. Looks like I might have been just a little too quick to push the refactor up :sweat_smile:.

**Review by 17cupsofcoffee — APPROVED** [review]
I'm happy with this, I think!

After playing around with this branch in dev tools, it looks like this leaves the performance *with* cached resources basically the same as it was, but for a fresh cache (e.g. a visitor coming in for the first time) it cuts the download size and the loading time in half, which is really good.

The maintainance burden doesn't seem like it'd be too high, as the files we're copying have been kept largely identical to their original versions (aside from changing the font paths, which isn't really avoidable). This means if we ever do need to update, it's basically just a matter of copying and pasting files.

**Comment by 17cupsofcoffee** [comment]
Thank you so much for the PR!

**Comment by BezPowell** [comment]
> Thank you so much for the PR!

Not a problem at all. I'm really glad I could help! I'm also glad we could manage to improve things in a way that doesn't add too much additional maintenance burden on you.

While I was going through I did spot a few minor changes that could be made to improve the accessibility of the page (mainly replacing the structural `div`s with more semantic equivalents). Would you be happy for me to have a play around with that when I next get some time and open another PR?

None of the a11y changes would alter the visual appearance of the page, just improve things for screen-reader users and crawlers.

**Comment by 17cupsofcoffee** [comment]
Any accessibility improvements would be welcomed (even if they did alter the visual appearence, within reason)!

Similar to the performance stuff, we've made _some_ improvements on that front (mainly around [color contrast](https://github.com/rust-gamedev/arewegameyet/blob/master/sass/_extra.scss#L91)), but I'd definitely love to make things even better where possible.

**Pull request merged**
