### PR TITLE
Add tataku game

### PR DESCRIPTION
**Pull request by ayyEve**
Sorry about the gif filesize, let me know if I should compress it further

### CODE REVIEW

**Review by ozkriff — CHANGES_REQUESTED** [review]
yeah, 12mb is too big, especially considering how small the gifs are on the site. could you scale the gif down, please? the expected file is approximately 2..4mb, iirc

**Comment by ayyEve** [comment]
Thanks for the tip, shrunk it down to 2.6MB

**Review by AngelOnFira — APPROVED** [review]
LGTM :+1:

**Review by ozkriff — APPROVED** [review]
:fire:

**Comment by ozkriff** [comment]
Tnx for the PR!

**Pull request merged**
