### PR TITLE
Add Plexus

### PR DESCRIPTION
**Pull request by olson-sean-k**
This change adds [Plexus](https://github.com/olson-sean-k/plexus) to the ecosystem registry in the "mesh" category. Plexus is a polygonal mesh processing crate that I've been developing. It is still missing important features; I'm not sure if there are any requirements for adding a crate to the registry. :sweat_smile: Please take a look. Thanks!

### CODE REVIEW

**Review by ozkriff — APPROVED** [review]
:+1: (replaced `source = "github"` with `source = "crates"`, zola should get info about github from the package's meta info)

**Comment by olson-sean-k** [comment]
Thanks for the merge! :smile:

One note: I intentionally referred to the GitHub repository because the published crates are unstable and, at the moment, very stale. I'd prefer that people who want to take a look check out the repository first. Sorry for not calling this out before.

**Comment by ozkriff** [comment]
@olson-sean-k oh. In this case, `crate_url` should be omitted otherwise it'll be shown as the main URL.

With

```toml
[[items]]
name = "olson-sean-k/plexus"
source = "github"
categories = ["mesh"]
homepage = "https://plexus.rs"
```

it'll look like this (homepage + github links only):

image

are you ok with this?

**Comment by olson-sean-k** [comment]
> In this case, crate_url should be omitted otherwise it'll be shown as the main URL.

Ah, gotcha. Sorry for mixing that up.

> it'll look like this (homepage + github links only): ... are you ok with this?

Sure, that looks good to me. :+1: Thanks for the help with this. I appreciate it!

**Comment by ozkriff** [comment]
Fixed in https://github.com/rust-gamedev/arewegameyet/commit/52c9e96e5adfc5657ce82ae29ff3dabcb3864262

**Pull request merged**
